### ISSUE TITLE
Unicode problem with URLs

### ISSUE THREAD

**Issue by reezer** [cobrateam/splinter#172] opened 2012-09-26 20:35 UTC
The following example:

```
# -*- coding: utf-8 -*-
from splinter.browser import Browser 
browser =     Browser('webdriver.chrome').visit(u'http://www.finden.at/Immobilien/6717898/Einfamilienhäuser-in-U1-Nähe')
```

raises an error:

```
Traceback (most recent call last):
  File "unicode_test.py", line 3, in <module>
    browser = Browser('webdriver.chrome').visit(u'http://www.finden.at/Immobilien/6717898/Einfamilienhäuser-in-U1-Nähe')
  File "/home/reezer/job/zoomsquare_django/venv/lib/python2.7/site-packages/splinter/driver/webdriver/__init__.py", line 77, in visit
    self.connect(url)
  File "/home/reezer/job/zoomsquare_django/venv/lib/python2.7/site-packages/splinter/request_handler/request_handler.py", line 17, in connect
    self._create_connection()
  File "/home/reezer/job/zoomsquare_django/venv/lib/python2.7/site-packages/splinter/request_handler/request_handler.py", line 40, in _create_connection
    self.conn.request('GET', self.path)
  File "/usr/lib/python2.7/httplib.py", line 958, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 992, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 790, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
 UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 36: ordinal not in range(128)
```

**Comment by andrewsmedina** [comment] 2020-01-04 18:59
I can't reproduce this bug in the splinter latest version. So, I'm closing it.

**Closed by andrewsmedina** 2020-01-04 18:59 UTC
Labels: NeedsInvestigation
