### ISSUE TITLE
Element is not clickable at point

### ISSUE THREAD

**Issue by tonylampada** [cobrateam/splinter#174] opened 2012-10-05 11:26 UTC
I got a few [failing tests](https://travis-ci.org/#!/freedomsponsors/www.freedomsponsors.org/builds/2671984) with this error:

```
...
  File "/home/travis/builds/freedomsponsors/www.freedomsponsors.org/djangoproject/core/tests/helpers/appdriver.py", line 230, in _fillOfferForm
1133    browser.find_by_id('btnSubmitOffer').click()
1134  File "/home/travis/virtualenv/python2.6/lib/python2.6/site-packages/splinter/driver/webdriver/__init__.py", line 364, in click
1135    self._element.click()
1136  File "/home/travis/virtualenv/python2.6/lib/python2.6/site-packages/selenium/webdriver/remote/webelement.py", line 52, in click
1137    self._execute(Command.CLICK_ELEMENT)
1138  File "/home/travis/virtualenv/python2.6/lib/python2.6/site-packages/selenium/webdriver/remote/webelement.py", line 205, in _execute
1139    return self._parent.execute(command, params)
1140  File "/home/travis/virtualenv/python2.6/lib/python2.6/site-packages/selenium/webdriver/remote/webdriver.py", line 156, in execute
1141    self.error_handler.check_response(response)
1142  File "/home/travis/virtualenv/python2.6/lib/python2.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 147, in check_response
1143    raise exception_class(message, screen, stacktrace)
1144WebDriverException: Message: u'Element is not clickable at point (637.5, 660). Other element would receive the click: <a href="/core/project">...
```

It seems like a [problem in chromedriver](http://code.google.com/p/selenium/issues/detail?id=2766#c27) - for which there's a workaround using javascript to scroll to an element's position (as suggested in comment 27, on that link)

But splinter elements to expose their (x, y), right? Is there a workaround for this?

**Comment by WillyWinkel** [comment] 2018-03-06 22:43
This is old and still open. I face the same issue. Are there any common workarounds or are you guys just don't get this error. If its the secondary, why am I getting it?

**Comment by WillyWinkel** [comment] 2018-03-06 22:46
I am facing this issue. Is there a common workaround?

**Comment by WillyWinkel** [comment] 2018-03-07 00:21
i noticed that calling `click()` twice solves the issue. First one throws, but scrolls so that the button is within the visible frame. Second one actually clicks.

**Comment by andrewsmedina** [comment] 2020-01-04 22:07
I cant reproduce this bug in the latest splinter version. So, I'm closing this issue.

**Closed by andrewsmedina** 2020-01-04 22:07 UTC
Labels: NeedsInvestigation
