### ISSUE TITLE
Unexpected behavior from setting profiles and extensions. 

### ISSUE THREAD

**Issue by orange-tsai** [cobrateam/splinter#570] opened 2017-11-01 01:52 UTC
Python = 2.7.10 (mac OS X Sierra)

Tried:
browser = Browser('firefox', extensions=['/full/path/to/ext.xpi', '/full/path/to/ext2.xpi'])
browser = Browser('firefox', extensions=['./ext.xpi', './ext2.xpi'])
With and without escape characters because it's in 'Application Support'
browser = Browser('firefox', profile=['/full/path/to/thingy.default, '/full/path/to/thing2.second'])
browser = Browser('firefox', profile=['./thingy.default, './thing2.second'])
Again With and without escape characters because it's in 'Application Support'

Even combined both extension and profile. None of it seems to work, always similar errors "[Errno 2] No such file or directory: ".

**Comment by impshum** [comment] 2018-09-26 09:06
I've never managed to get a profile loaded with Splinter. I'm in the same boat here.

**Comment by jsfehler** [comment] 2021-07-22 21:59
Dupe of #427

**Closed by jsfehler** 2021-07-22 21:59 UTC
Labels: NeedsInvestigation
