### ISSUE TITLE
transfer project ownership to jazzband

### ISSUE THREAD

**Issue by deronnax** [cobrateam/splinter#1028] opened 2022-04-12 20:53 UTC
Hello @jsfehler . Cobrateam seems dead and splinter does not see much activity.
Would you please consider transferring ownership to [Jazzband](https://github.com/jazzband/)? It's an organization of volunteer python maintainers specialized in the python ecosystem. I appreciate splinter and I would like for it to keep living.
Thank you very much.

**Comment by jsfehler** [comment] 2022-04-12 22:32
@deronnax I'm not the maintainer of this repo, nor do I have the power to transfer ownership.

**Comment by deronnax** [comment] 2022-04-13 10:57
Hello. Thanks for your reply. Do you still have any contact with the original team?

**Comment by fsouza** [comment] 2022-04-17 13:06
Hey @deronnax, thanks for opening this issue. I'm not totally familiar with jazzband, but I personally feel like having more collaborators/maintainers in the project would make more sense that simply moving it? And I think we should just have people continue to send pull requests and evolve into collaborators/maintainers. Is that too slow? Or is the idea that by being a project in jazzband splinter will attract more contributors? What's preventing those contributors from contributing today?

To be fair, I don't think my opinion matters very much at this point, so I'll defer to @jsfehler as the most active collaborator and @andrewsmedina as basically the only active maintainer 🙈 

@andrewsmedina not sure how you feel about this. I know you've done some Splinter stuff more recently than I have, and you still do it every now and then. Would the transfer make sense to you? I imagine you'd want to keep your current access (maintainer) if we do transfer it?

@jsfehler what's your opinion on this?

**Comment by andrewsmedina** [comment] 2022-04-19 18:14
Hi @deronnax, thanks for opening this issue. 

What problem we want to solve to moving the splinter to jazzband organization? What is not working now that will work better after move this repo to jazzband org.

I have participated in a repo migration to jazzband, and this move has not change the engagement and contribution in that case.

I believe that will be nice to have more contributors and more people working on splinter , by I really believe that change the repository owner is not the solution for that.

**Comment by jsfehler** [comment] 2022-04-20 00:05
I don't think jazzband is appropriate given the current state of the project.

Jazzband makes sense for projects that have many potential contributors but no maintainers for chores such as PR review and releases. It's an alternative to forking a dead project.

Splinter doesn't have enough active contributors to justify the move.

@andrewsmedina If you add me as a contributor on readthedocs and pypi I can handle the occasional release.

**Comment by fsouza** [comment] 2022-04-20 00:20
Could we automate releases? Like, @jsfehler or another maintainer could push a tag and then GitHub Actions would push it to pypi and readthedocs?

**Comment by andrewsmedina** [comment] 2022-04-20 02:48
@jsfehler to make a release what do you need is to be added in pypi and to run the `make release version=new-version`.  Please, pass in private your pypi account.

@fsouza I really don't know if there is a way to integrate this process with github action, but its is a very good idea.

**Comment by deronnax** [comment] 2022-04-21 09:06
Could you also create a dedicated splinter Github organization with access to many people? I am afraid one day the people behind the Cobrateam organization just stop showing up (because they have gone to do other things in life) and the ownership of the project is lost with everybody locked out and the project de facto staled.

I have seen this *so many* times on Github.

**Comment by fsouza** [comment] 2022-04-21 15:00
> Could you also create a dedicated splinter Github organization with access to many people? I am afraid one day the people behind the Cobrateam organization just stop showing up (because they have gone to do other things in life), especially since Cobrateam itself is dead, and the ownership of the project is lost with everybody locked out and the project de facto staled.

Who would those people be? We're not against adding people to cobrateam, but in general we'd want to add people who would be contributors/maintainers of the project, and it feels a bit weird to add people who have never contributed to the project as maintainers. I think the traditional path (third party contributor -> contributor -> maintainer) still applies and we should really only take action if we see PRs piling up or if me or Andrews are completely gone?

Preemptively opening an issue in a project to move it to an org to make sure it never dies isn't really productive since there's no particular reason to pick a project over the other to open an issue like this. Like any project could be a target of such an issue, and I'd be curious on what made you pick cobrateam/splinter. Like, did you have some interaction/PR where you felt like this could've moved faster? Or is this some sort of general concern about the ecosystem? (which I totally respect btw)

**Comment by deronnax** [comment] 2022-04-22 08:37
The company owning the GitHub organization of splinter disappeared, that is why I opened the issue. I have seen so many Github projects dying when it happens because original developers walk away and access to the original Github organization is lost and the project itself get lost (original developers walked away without giving access to other people and everybody is locked out). You can fork but it is never the same.

Here though, it seems despite the company's disappearance, developers still have access and still contribute, that's cool. But for how long?

On the other hand, why keep the Cobrateam organization and why not create a dedicated splinter organization? I did not ask to add anybody, you can just keep the people currently in the Cobrateam one.

**Comment by deronnax** [comment] 2022-04-22 08:41
I want to emphasize that I really truly appreciate Splinter, that's what I opened the issue: I am seeing a dangerous pattern I have noticed many times before (the owning org died) and I don't want to see splinter stale and die. Btw I don't even to be a member of the new organization. That's it.

Btw cheers to you guys, thank you 1000 times for your awesome. Doing pure Selenium is awful, thanks god there is Splinter.

**Comment by andrewsmedina** [comment] 2022-04-25 19:48
> On the other hand, why keep the Cobrateam organization and why not create a dedicated splinter organization? I did not ask to add anybody, you can just keep the people currently in the Cobrateam one.

@deronnax I understand your concerns, but I believe that the problem is when the maintainers stop to maintain the project and not with the organization itself. 

I agree with @fsouza that changes the org, will not change the state of the project. And the state of the project is that Splinter has 3 maintainers (@fsouza, @jsfehler and me) and we are open for contributors and maintainers.

**Comment by deronnax** [comment] 2022-04-25 21:19
Well then. I don't insist.

**Comment by fsouza** [comment] 2022-04-25 21:45
> The company owning the GitHub organization of splinter disappeared, that is why I opened the issue. I have seen so many Github projects dying when it happens because original developers walk away and access to the original Github organization is lost and the project itself get lost (original developers walked away without giving access to other people and everybody is locked out). You can fork but it is never the same.

Don't mean to drag on this, but I think there's some confusion here: cobrateam was never owned by any company. It was started by @andrewsmedina and other folks that never worked together in the same company and knew each other from the Python Brasil community.

There was a time where most of the members of the cobrateam organization worked at @globocom, but that company has never owned the org (and they're definitely not going anywhere, so I assume you must be thinking of some other company). Also, there was never a time where all members of the organization worked at the same company.

To be clear, I do appreciate the concerns and am willing to revisit this at any time, but I don't think that moving this to a different organization will change much of the current state of the project.

**Closed** 2022-05-03 02:50 UTC
