### ISSUE TITLE
test execution stalls on with iframe as

### ISSUE THREAD

**Issue by IanHeffernan** [cobrateam/splinter#169] opened 2012-09-13 15:42 UTC
Hi,
I have a test that opens a link in an iframe in a page.

<pre>self.browser.parent_window = self.browser.current_window 
with self.browser.get_iframe('document_frame') as frame:
    frame.click_link_by_text("sampledocument2")
assert self.browser.is_text_present("Version as of Jan 1st, 2009")</pre>

The assert statement is never executed. Is there a way to pass execution back to the main browser from the frame?

Thanks & Regards

Ian Heffernan

**Comment by jsfehler** [comment] 2020-01-07 20:44
@andrewsmedina I can't reproduce this issue, and there's tests to validate iframes. The issue is over 7 years old, so 🤷‍♂

**Comment by andrewsmedina** [comment] 2020-01-09 20:06
@jsfehler I will close this issue ;)

**Closed by andrewsmedina** 2020-01-09 20:06 UTC
Labels: NeedsInvestigation
