### ISSUE TITLE
[Bug] Unicode issue

### ISSUE THREAD

**Issue by GeorgeFischhof** [cobrateam/splinter#504] opened 2016-08-16 09:08 UTC
Hi There,

on a hungarian language page there was a problem during encoding browser.html
any usage of browser.html for example printing it causes:

Error message:
**\* UnicodeEncodeError: 'charmap' codec can't encode character '\u0151' in position 0: character maps to <undefined>
The letter is: ő (o with 2 lines on the top)

The page header:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="hu-HU" lang="hu-HU" dir="ltr">

<head>

<meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>

used software:
python 3.5.1
selenium (2.53.6)
splinter (0.7.4)

FireFox: 47.0.1

BR,
George

**Comment by andrewsmedina** [comment] 2016-08-17 01:13
thank you for report, I will try to reproduce it

**Comment by andrewsmedina** [comment] 2019-12-12 03:09
I can't reproduce this bug with the latests splinter versions. So, I'm closing it for now

**Closed by andrewsmedina** 2019-12-12 03:09 UTC
Labels: NeedsInvestigation, bug
